baseURL = "https://developer.bring.com"
languageCode = "en-us"
title = "Bring Developer"
pluralizelisttitles = false
pygmentsUseClasses = true
summaryLength = 60
paginate = 10

[markup.highlight]
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Documentation for developers."
ramlBuiltinTypes = [
  "any",
  "object",
  "array",
  "number",
  "boolean",
  "string",
  "date-only",
  "time-only",
  "datetime-only",
  "datetime",
  "file",
  "integer",
  "nil"
]
apis = [
  "content/api/event-cast/api.raml",
  "content/api/invoice/api.raml",
  "content/api/reports/api.raml",
  "content/api/shipment/api.raml",
  "content/api/tracking/api.raml",
  "content/api/pickup-point/api.raml"
]

[taxonomies]
tag = "tags"

[menu]

  [[menu.api]]
    title = "API Status"
    url = "https://status.bring.systems"
    weight = 1000
    [menu.api.params]
      blank = "target=\"_blank\" rel=\"noopener noreferrer\""
