baseURL = "https://developer.bring.com"
publishDir = "_site"
languageCode = "en-us"
title = "Bring Developer"
pluralizelisttitles = false
pygmentsUseClasses = true
summaryLength = 60
paginate = 10
ignorefiles = ["css/main.js"]
disqusShortname = "bringdev"

[markup.highlight]
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = false

[params]
description = "Documentation for developers."
ramlBuiltinTypes = [
  "any",
  "object",
  "array",
  "number",
  "boolean",
  "string",
  "date-only",
  "time-only",
  "datetime-only",
  "datetime",
  "file",
  "integer",
  "nil"
]
apis = [
  "content/api/booking/api.raml",
  "content/api/shipping-guide/api.raml",
  "content/api/shipping-guide_2/api.raml",
  "content/api/warehousing/api.raml",
  "content/api/order-management/api.raml",
  "content/api/postal-code/api.raml",
  "content/api/modify-delivery/api.raml",
  "content/api/event-cast/api.raml",
  "content/api/invoice/api.raml",
  "content/api/reports/api.raml",
  "content/api/shipment/api.raml",
  "content/api/tracking/api.raml",
  "content/api/pickup-point/api.raml"
]

[taxonomies]
tag = "tags"

[menu]

[[menu.api]]
title = "API status"
url = "https://status.bring.systems"
weight = 1000

[menu.api.params]
blank = "target=\"_blank\" rel=\"noopener noreferrer\""
